-- Add TMS load sheet metadata fields and extend LoadType with equipment labels.
ALTER TYPE "LoadType" ADD VALUE IF NOT EXISTS 'VAN';
ALTER TYPE "LoadType" ADD VALUE IF NOT EXISTS 'REEFER';
ALTER TYPE "LoadType" ADD VALUE IF NOT EXISTS 'FLATBED';
ALTER TYPE "LoadType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TABLE "Load"
  ADD COLUMN IF NOT EXISTS "externalTripId" VARCHAR(64),
  ADD COLUMN IF NOT EXISTS "salesRepName" VARCHAR(128),
  ADD COLUMN IF NOT EXISTS "dropName" VARCHAR(128),
  ADD COLUMN IF NOT EXISTS "notes" TEXT,
  ADD COLUMN IF NOT EXISTS "desiredInvoiceDate" TIMESTAMP(3);
