export const DISPATCH_EXECUTION_ROLES = ["ADMIN", "DISPATCHER", "HEAD_DISPATCHER"] as const;

export const DISPATCH_EXECUTION_OR_BILLING_ROLES = [
  ...DISPATCH_EXECUTION_ROLES,
  "BILLING",
] as const;

export const DISPATCH_TRACKING_ROLES = [...DISPATCH_EXECUTION_ROLES, "DRIVER"] as const;
