-- Pre-add enum values so later migrations can safely use them in data updates
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BOL';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'LUMPER';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCALE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DETENTION';

ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'DISPUTED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'SHORT_PAID';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'VOID';

ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SETTLEMENT_GENERATED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SETTLEMENT_FINALIZED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SETTLEMENT_PAID';
